+define+DEVEL_CXL
+incdir+${CMSS_HOME}/design/sverilog
${CMSS_HOME}/design/sverilog/APB_IF.sv
${CMSS_HOME}/design/sverilog/AXI4_IF.sv
${CMSS_HOME}/design/sverilog/CPI_IF.sv
${CMSS_HOME}/design/sverilog/PIPE_IF.sv
${CMSS_HOME}/design/sverilog/CMSS_IF.sv
${CMSS_HOME}/design/sverilog/SAL_ARBITER_RR.sv
${CMSS_HOME}/design/sverilog/SAL_DELAY.sv
${CMSS_HOME}/design/sverilog/SAL_FIFO.sv
${CMSS_HOME}/design/sverilog/SAL_FR_REGISTER_SLICE.sv
${CMSS_HOME}/design/sverilog/SAL_DESERIALIZE_FIFO.sv
${CMSS_HOME}/design/sverilog/SAL_SERIALIZE_FIFO.sv
${CMSS_HOME}/design/sverilog/SAL_SERDES_FIFO.sv
${CMSS_HOME}/design/sverilog/SAL_SDP_RAM.sv
${CMSS_HOME}/design/sverilog/SAL_SOP_GEN.sv
${CMSS_HOME}/design/sverilog/SAL_REORDER_BUFFER.sv
${CMSS_HOME}/design/sverilog/CMSS_CPI_AGENT_CONNECT.sv
${CMSS_HOME}/design/sverilog/CMSS_CPI_FABRIC_CONNECT.sv
${CMSS_HOME}/design/sverilog/CMSS_CPI_TX_CONNECT.sv
${CMSS_HOME}/design/sverilog/CMSS_CPI_RX_CONNECT.sv
${CMSS_HOME}/design/sverilog/CMSS_CACHE_CFG_pkg.sv
${CMSS_HOME}/design/sverilog/CMSS_CACHE_CFG.sv
${CMSS_HOME}/design/sverilog/CMSS_CACHE_CORE_W_CTRL.sv
${CMSS_HOME}/design/sverilog/CMSS_CACHE_CORE_R_CTRL.sv
${CMSS_HOME}/design/sverilog/CMSS_CACHE_CORE_B_CTRL.sv
${CMSS_HOME}/design/sverilog/CMSS_CACHE_MEM_AR_CTRL.sv
${CMSS_HOME}/design/sverilog/CMSS_CACHE_MEM_AW_CTRL.sv
${CMSS_HOME}/design/sverilog/CMSS_CACHE_MEM_W_CTRL.sv
${CMSS_HOME}/design/sverilog/CMSS_CACHE_MEM_R_CTRL.sv
${CMSS_HOME}/design/sverilog/CMSS_CACHE_MEM_B_CTRL.sv
${CMSS_HOME}/design/sverilog/CMSS_CACHE_MD_BUFFER.sv
${CMSS_HOME}/design/sverilog/CMSS_CACHE_CMD_HANDLER.sv
${CMSS_HOME}/design/sverilog/CMSS_CACHE_ID_MANAGER.sv
${CMSS_HOME}/design/sverilog/CMSS_CACHE_D2H_REQ_CTRL.sv
${CMSS_HOME}/design/sverilog/CMSS_CACHE_D2H_DATA_CTRL.sv
${CMSS_HOME}/design/sverilog/CMSS_CACHE_H2D_DATA_CTRL.sv
${CMSS_HOME}/design/sverilog/CMSS_CACHE_H2D_RSP_CTRL.sv
${CMSS_HOME}/design/sverilog/CPI_RX_BUFFER.sv
${CMSS_HOME}/design/sverilog/CMSS_CACHE_TOP.sv
${CMSS_HOME}/design/sverilog/CMSS_CACHE_TOP_WRAPPER.sv
${CMSS_HOME}/design/sverilog/CMSS_CACHE_TOP_XLNX_WRAPPER.v
${CMSS_HOME}/design/sverilog/CMSS_MEM_TOP.sv
${CMSS_HOME}/design/sverilog/CMSS_CXL_D2H_DATA_CTRL.sv
${CMSS_HOME}/design/sverilog/CMSS_CXL_D2H_REQ_CTRL.sv
${CMSS_HOME}/design/sverilog/CMSS_CXL_D2H_RSP_CTRL.sv
${CMSS_HOME}/design/sverilog/CMSS_CXL_H2D_RSP_CTRL.sv
${CMSS_HOME}/design/sverilog/CMSS_CXL_H2D_DATA_CTRL.sv
${CMSS_HOME}/design/sverilog/CMSS_CXL_TX_PACK.sv
${CMSS_HOME}/design/sverilog/CMSS_CXL_TX_INIT.sv
${CMSS_HOME}/design/sverilog/CMSS_CXL_TX_LLCTRL.sv
${CMSS_HOME}/design/sverilog/CMSS_CXL_TX_CREDIT_UPDATE.sv
${CMSS_HOME}/design/sverilog/CMSS_CXL_TX_CREDIT.sv
${CMSS_HOME}/design/sverilog/CMSS_CXL_TX_RETRY.sv
${CMSS_HOME}/design/sverilog/CMSS_CXL_TX_ARBITER.sv
${CMSS_HOME}/design/sverilog/CMSS_CXL_TX_CRC_ENC.sv
${CMSS_HOME}/design/sverilog/CMSS_CXL_RX_INIT.sv
${CMSS_HOME}/design/sverilog/CMSS_CXL_RX_RETRY.sv
${CMSS_HOME}/design/sverilog/CMSS_CXL_RX_LLCTRL.sv
${CMSS_HOME}/design/sverilog/CMSS_CXL_RX_CRC_DEC.sv
${CMSS_HOME}/design/sverilog/CMSS_CXL_RX_UNPACK.sv
${CMSS_HOME}/design/sverilog/CMSS_CXL_TOP.sv
${CMSS_HOME}/design/sverilog/CMSS_TOP.sv
${CMSS_HOME}/design/sverilog/CMSS_TOP_WRAPPER.sv
